[2022-05-30 20:21:36,078] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-05-30 20:21:36,470] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-05-30 20:21:36,485] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:36,490] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 20:21:36,491] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:36,901] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-03-02 06:00:00+00:00
[2022-05-30 20:21:37,138] {standard_task_runner.py:52} INFO - Started process 1303 to run task
[2022-05-30 20:21:37,294] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-03-02T06:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpi70mzsha', '--error-file', '/tmp/tmprcqq_m0u']
[2022-05-30 20:21:37,331] {standard_task_runner.py:80} INFO - Job 142: Subtask ingest
[2022-05-30 20:21:39,356] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-03-02T06:00:00+00:00 [running]> on host e083cbf9476b
[2022-05-30 20:21:41,014] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 20:21:41,827] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-03-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-02T06:00:00+00:00
[2022-05-30 20:21:41,882] {logging_mixin.py:115} INFO - yellow_taxi_2021_03 /opt/***/output_2021-03.parquet 2021-03-02T06:00:00+00:00
[2022-05-30 20:21:41,902] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 12, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 711, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 772, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2022-05-30 20:21:42,035] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210302T060000, start_date=20220530T202136, end_date=20220530T202142
[2022-05-30 20:21:42,346] {standard_task_runner.py:97} ERROR - Failed to execute job 142 for task ingest (invalid literal for int() with base 10: 'None'; 1303)
[2022-05-30 20:21:42,632] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-05-30 20:21:42,686] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1303. PIDs of all processes in the group: [1303]
[2022-05-30 20:21:42,705] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1303
[2022-05-30 20:21:42,718] {process_utils.py:75} INFO - Process psutil.Process(pid=1303, status='terminated', exitcode=1, started='20:21:37') (1303) terminated with exit code 1
[2022-05-30 22:16:49,368] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-05-30 22:16:49,396] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-05-30 22:16:49,398] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:16:49,399] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:16:49,402] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:16:49,452] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-03-02 06:00:00+00:00
[2022-05-30 22:16:49,532] {standard_task_runner.py:52} INFO - Started process 1332 to run task
[2022-05-30 22:16:49,558] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-03-02T06:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpj8uzvncm', '--error-file', '/tmp/tmphyjceaap']
[2022-05-30 22:16:49,569] {standard_task_runner.py:80} INFO - Job 215: Subtask ingest
[2022-05-30 22:16:49,740] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-03-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:16:50,039] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:16:50,133] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-03-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-02T06:00:00+00:00
[2022-05-30 22:16:50,138] {logging_mixin.py:115} INFO - yellow_taxi_2021_03 /opt/***/output_2021-03.parquet 2021-03-02T06:00:00+00:00
[2022-05-30 22:16:50,189] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:17:05,305] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-05-30 22:17:05,371] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210302T060000, start_date=20220530T221649, end_date=20220530T221705
[2022-05-30 22:17:06,011] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 22:21:03,639] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-05-30 22:21:03,721] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-05-30 22:21:03,723] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:21:03,724] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:21:03,725] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:21:03,788] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-03-02 06:00:00+00:00
[2022-05-30 22:21:03,817] {standard_task_runner.py:52} INFO - Started process 1724 to run task
[2022-05-30 22:21:03,842] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-03-02T06:00:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmppo2jkkab', '--error-file', '/tmp/tmp39pia41k']
[2022-05-30 22:21:03,846] {standard_task_runner.py:80} INFO - Job 246: Subtask ingest
[2022-05-30 22:21:04,043] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-03-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:21:04,153] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:21:04,259] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-03-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-02T06:00:00+00:00
[2022-05-30 22:21:04,262] {logging_mixin.py:115} INFO - yellow_taxi_2021_03 /opt/***/output_2021-03.parquet 2021-03-02T06:00:00+00:00
[2022-05-30 22:21:04,305] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:23:38,197] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-05-30 22:23:40,561] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1724. PIDs of all processes in the group: [1724]
[2022-05-30 22:23:40,580] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1724
[2022-05-30 22:24:40,803] {process_utils.py:143} WARNING - process psutil.Process(pid=1724, name='airflow task ru', status='running', started='22:21:03') did not respond to SIGTERM. Trying SIGKILL
[2022-05-30 22:24:42,606] {process_utils.py:80} INFO - Sending the signal Signals.SIGKILL to group 1724
[2022-05-30 22:25:39,524] {process_utils.py:75} INFO - Process psutil.Process(pid=1724, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='22:21:03') (1724) terminated with exit code Negsignal.SIGKILL
[2022-05-30 22:25:39,536] {standard_task_runner.py:162} ERROR - Job 246 was killed before it finished (likely due to running out of memory)
