[2022-05-30 20:21:41,335] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 20:21:41,603] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 20:21:41,609] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:41,614] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 20:21:41,619] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:41,760] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2022-03-02 06:00:00+00:00
[2022-05-30 20:21:41,853] {standard_task_runner.py:52} INFO - Started process 1310 to run task
[2022-05-30 20:21:41,940] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp3xo7gqh8', '--error-file', '/tmp/tmpcudk3__8']
[2022-05-30 20:21:41,981] {standard_task_runner.py:80} INFO - Job 147: Subtask ingest
[2022-05-30 20:21:42,707] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [running]> on host e083cbf9476b
[2022-05-30 20:21:43,059] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 20:21:43,330] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2022-05-30 20:21:43,336] {logging_mixin.py:115} INFO - yellow_taxi_2022_03 /opt/***/output_2022-03.parquet 2022-03-02T06:00:00+00:00
[2022-05-30 20:21:43,352] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 12, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 711, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 772, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2022-05-30 20:21:43,414] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20220302T060000, start_date=20220530T202141, end_date=20220530T202143
[2022-05-30 20:21:43,507] {standard_task_runner.py:97} ERROR - Failed to execute job 147 for task ingest (invalid literal for int() with base 10: 'None'; 1310)
[2022-05-30 20:21:43,631] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-30 20:21:43,826] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 20:28:33,079] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 20:28:33,090] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 20:28:33,091] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:28:33,092] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 20:28:33,093] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:28:33,108] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2022-03-02 06:00:00+00:00
[2022-05-30 20:28:33,125] {standard_task_runner.py:52} INFO - Started process 1721 to run task
[2022-05-30 20:28:33,138] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp0odeqund', '--error-file', '/tmp/tmpnyydlc98']
[2022-05-30 20:28:33,141] {standard_task_runner.py:80} INFO - Job 158: Subtask ingest
[2022-05-30 20:28:33,365] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [running]> on host e083cbf9476b
[2022-05-30 20:28:33,451] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 20:28:33,547] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2022-05-30 20:28:33,554] {logging_mixin.py:115} INFO - yellow_taxi_2022_03 /opt/***/output_2022-03.parquet 2022-03-02T06:00:00+00:00
[2022-05-30 20:28:33,557] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 12, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 711, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 772, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2022-05-30 20:28:33,589] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20220302T060000, start_date=20220530T202833, end_date=20220530T202833
[2022-05-30 20:28:33,608] {standard_task_runner.py:97} ERROR - Failed to execute job 158 for task ingest (invalid literal for int() with base 10: 'None'; 1721)
[2022-05-30 20:28:33,675] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-30 20:28:33,724] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 21:14:23,460] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 21:14:23,474] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 21:14:23,475] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 21:14:23,477] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 21:14:23,478] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 21:14:23,493] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2022-03-02 06:00:00+00:00
[2022-05-30 21:14:23,501] {standard_task_runner.py:52} INFO - Started process 293 to run task
[2022-05-30 21:14:23,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpju6h7k77', '--error-file', '/tmp/tmpu8li390y']
[2022-05-30 21:14:23,510] {standard_task_runner.py:80} INFO - Job 12: Subtask ingest
[2022-05-30 21:14:23,578] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [running]> on host 973151ef250d
[2022-05-30 21:14:23,618] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 21:14:23,659] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2022-05-30 21:14:23,662] {logging_mixin.py:115} INFO - yellow_taxi_2022_03 /opt/***/output_2022-03.parquet 2022-03-02T06:00:00+00:00
[2022-05-30 21:14:23,678] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "pgdatabase" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 13, in ingest_callable
    engine.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "pgdatabase" to address: Name or service not known

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2022-05-30 21:14:23,695] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20220302T060000, start_date=20220530T211423, end_date=20220530T211423
[2022-05-30 21:14:23,705] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task ingest ((psycopg2.OperationalError) could not translate host name "pgdatabase" to address: Name or service not known

(Background on this error at: http://sqlalche.me/e/14/e3q8); 293)
[2022-05-30 21:14:23,720] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-30 21:14:23,749] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 22:12:37,632] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 22:12:37,709] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 22:12:37,711] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:12:37,713] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:12:37,715] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:12:37,765] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2022-03-02 06:00:00+00:00
[2022-05-30 22:12:37,800] {standard_task_runner.py:52} INFO - Started process 1008 to run task
[2022-05-30 22:12:37,815] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpc_0cgpdl', '--error-file', '/tmp/tmpbzjgaj73']
[2022-05-30 22:12:37,820] {standard_task_runner.py:80} INFO - Job 195: Subtask ingest
[2022-05-30 22:12:38,011] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:12:38,206] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:12:38,357] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2022-05-30 22:12:38,375] {logging_mixin.py:115} INFO - yellow_taxi_2022_03 /opt/***/output_2022-03.parquet 2022-03-02T06:00:00+00:00
[2022-05-30 22:12:38,458] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:12:59,207] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-05-30 22:12:59,240] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20220302T060000, start_date=20220530T221237, end_date=20220530T221259
[2022-05-30 22:12:59,278] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 22:17:21,490] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 22:17:21,795] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 22:17:21,809] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:17:21,812] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:17:21,813] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:17:22,047] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2022-03-02 06:00:00+00:00
[2022-05-30 22:17:22,196] {standard_task_runner.py:52} INFO - Started process 1409 to run task
[2022-05-30 22:17:22,327] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpgedxm13z', '--error-file', '/tmp/tmpk7ybxshn']
[2022-05-30 22:17:22,391] {standard_task_runner.py:80} INFO - Job 222: Subtask ingest
[2022-05-30 22:17:23,300] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:17:24,047] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:17:27,322] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2022-05-30 22:17:27,389] {logging_mixin.py:115} INFO - yellow_taxi_2022_03 /opt/***/output_2022-03.parquet 2022-03-02T06:00:00+00:00
[2022-05-30 22:17:27,630] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:17:49,775] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-05-30 22:17:49,850] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20220302T060000, start_date=20220530T221721, end_date=20220530T221749
[2022-05-30 22:17:49,995] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 22:25:30,889] {taskinstance.py:1154} INFO - Dependencies not met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-05-30 22:25:30,915] {local_task_job.py:101} INFO - Task is not able to be run
[2022-05-30 22:28:53,091] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 22:28:53,098] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-05-30 22:28:53,099] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:28:53,100] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:28:53,100] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:28:53,108] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2022-03-02 06:00:00+00:00
[2022-05-30 22:28:53,113] {standard_task_runner.py:52} INFO - Started process 2174 to run task
[2022-05-30 22:28:53,116] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpc0btwq4r', '--error-file', '/tmp/tmpk6og2_fy']
[2022-05-30 22:28:53,117] {standard_task_runner.py:80} INFO - Job 267: Subtask ingest
[2022-05-30 22:28:53,153] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2022-03-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:28:53,176] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:28:53,201] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2022-05-30 22:28:53,203] {logging_mixin.py:115} INFO - yellow_taxi_2022_03 /opt/***/output_2022-03.parquet 2022-03-02T06:00:00+00:00
[2022-05-30 22:28:53,236] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:29:11,992] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-05-30 22:29:12,036] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20220302T060000, start_date=20220530T222853, end_date=20220530T222912
[2022-05-30 22:29:12,066] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
