[2022-05-30 20:21:09,588] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2021-05-30T17:20:04-03:00 [queued]>
[2022-05-30 20:21:09,912] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2021-05-30T17:20:04-03:00 [queued]>
[2022-05-30 20:21:09,920] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:09,922] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 20:21:09,929] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:10,341] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-05-30 20:20:04+00:00
[2022-05-30 20:21:10,912] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'manual__2021-05-30T17:20:04-03:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpfp86oz8w', '--error-file', '/tmp/tmpdo0_dsbs']
[2022-05-30 20:21:11,237] {standard_task_runner.py:80} INFO - Job 132: Subtask ingest
[2022-05-30 20:21:10,885] {standard_task_runner.py:52} INFO - Started process 1264 to run task
[2022-05-30 20:21:13,518] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest manual__2021-05-30T17:20:04-03:00 [running]> on host e083cbf9476b
[2022-05-30 20:21:14,344] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 20:21:15,726] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-05-30T20:20:04+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-30T17:20:04-03:00
[2022-05-30 20:21:15,810] {logging_mixin.py:115} INFO - yellow_taxi_2021_05 /opt/***/output_2021-05.parquet 2021-05-30T20:20:04+00:00
[2022-05-30 20:21:15,837] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 12, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 711, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 772, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2022-05-30 20:21:16,645] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210530T202004, start_date=20220530T202109, end_date=20220530T202116
[2022-05-30 20:21:17,643] {standard_task_runner.py:97} ERROR - Failed to execute job 132 for task ingest (invalid literal for int() with base 10: 'None'; 1264)
[2022-05-30 20:21:17,761] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-05-30 20:21:18,016] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1264. PIDs of all processes in the group: [1264]
[2022-05-30 20:21:18,052] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1264
[2022-05-30 20:21:19,323] {process_utils.py:75} INFO - Process psutil.Process(pid=1264, status='terminated', exitcode=1, started='20:21:10') (1264) terminated with exit code 1
